const test=require('node:test'); const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const M=require('../src/model.js');const root=path.join(__dirname,'..');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'data/manifest.json')));
const raw=M.parseCSV(fs.readFileSync(path.join(root,'data/transactions.csv'),'utf8'));
const expected=JSON.parse(fs.readFileSync(path.join(root,'data/expected.json')));
const data=M.prepare(manifest,raw), all=M.calculate(data);
for(const [key,value] of Object.entries(expected.RUB)) test('golden: '+key,()=>assert.equal(all.metrics[key].toString(),value));
for(const [key,value] of Object.entries(expected.counts)) test('golden: '+key,()=>assert.equal(all.counts[key],value));
test('precision: 0.10 + 0.20 = 0.30',()=>assert.equal(M.parseMoney('0.10')+M.parseMoney('0.20'),30n));
test('reject non-exact decimal',()=>assert.throws(()=>M.parseMoney('1.005')));
test('same identity, changed amount is a conflict',()=>assert.throws(()=>M.prepare(manifest,[...raw,{...raw[0],amount:'999.00',minor:99900n}]),/IDENTITY_CONFLICT/));
test('same identity, changed status is a conflict',()=>assert.throws(()=>M.prepare(manifest,[...raw,{...raw[0],status:'pending'}]),/IDENTITY_CONFLICT/));
test('checking: cash, expense and scope',()=>{const s=M.calculate(data,'checking');assert.equal(s.metrics.closing_cash_minor,21550000n);assert.equal(s.metrics.net_spending_minor,850000n);assert(s.rows.every(r=>r.account_id==='checking'));assert.equal(s.counts.duplicate_observations,1);});
test('savings: own transfer is not income',()=>{const s=M.calculate(data,'savings');assert.equal(s.metrics.income_minor,0n);assert.equal(s.metrics.cash_movement_minor,2000000n);assert.equal(s.metrics.closing_cash_minor,7000000n);});
test('card: repayment is not income and refund reduces spending',()=>{const s=M.calculate(data,'card');assert.equal(s.metrics.income_minor,0n);assert.equal(s.metrics.net_spending_minor,750000n);assert.equal(s.metrics.closing_liability_minor,150000n);assert.equal(s.metrics.cash_movement_minor,0n);});
test('subperiod balance unavailable, not reused',()=>{const s=M.calculate(data,'all','first');assert.equal(s.metrics.closing_cash_minor,null);assert.equal(s.counts.pending_transactions,0);assert.equal(s.metrics.income_minor,15000000n);});
test('last half: pending remains excluded',()=>{const s=M.calculate(data,'all','last');assert.equal(s.metrics.net_spending_minor,0n);assert.equal(s.counts.pending_transactions,1);assert.equal(s.metrics.closing_cash_minor,null);});
test('daily cash movement reconciles exactly',()=>assert.equal(all.daily.at(-1).value_minor,all.metrics.cash_movement_minor.toString()));
test('expense breakdown matches net spending',()=>assert.equal(all.categories.reduce((s,c)=>s+c.minor,0n),all.metrics.net_spending_minor));
test('raw duplicate not exported a second time',()=>assert.equal(M.csvExport(all.rows).split('"groceries-1"').length-1,1));
test('CSV export respects displayed local filters',()=>{const rows=M.filterTable(M.calculate(data,'checking'),'income','freelance');assert.equal(rows.length,1);const csv=M.csvExport(rows);assert(csv.includes('freelance-1'));assert(!csv.includes('salary-1'));});
test('pending table filter returns only pending',()=>assert.equal(M.filterTable(all,'pending').length,1));
test('invalid account or period rejected',()=>{assert.throws(()=>M.calculate(data,'missing'));assert.throws(()=>M.calculate(data,'all','missing'));});
